### ISSUE TITLE
Installed, connected but...

### ISSUE THREAD

**Issue by IDEA-ONLINE** [ne-znam/neznam-atproto-share#2]
Hello, I installed the plugin, connected it to to bluesky, the cronjob is there but...
Nothing happens. Can you please help me?

With kind regards from Holland

**Comment by mbanusic** [comment]
Of course, can you verify that our cron job has run? You can use a plugin like [WP Control](https://wordpress.org/plugins/wp-crontrol/) to verify:
![Screenshot 2023-10-31 at 11 21 31](https://github.com/ne-znam/neznam-atproto-share/assets/694907/1b62c4a2-859d-49ae-947e-63c31adfefd9)


Also verify that you have checked the check to publish to Atproto:
![Screenshot 2023-10-31 at 11 22 11](https://github.com/ne-znam/neznam-atproto-share/assets/694907/9c6246aa-f8d0-47b9-9075-5610e0040124)

**Comment by IDEA-ONLINE** [comment]
Cronjob works as far as I can see:
<html><body>


rsssl_every_five_minutes_hookBewerken \| Draai nu \| Pauzeer deze hook \| Verwijderen | Geen | 2023-10-31 13:12:353 minuten 19 seconden | rsssl_every_five_minutes_cron() | Once every 5 minutes
-- | -- | -- | -- | --



</body>
</html>rsssl_every_five_minutes_hook
[Bewerken](https://www.berkelland.net/wp-admin/tools.php?page=crontrol_admin_manage_page&crontrol_action=edit-cron&crontrol_id=rsssl_every_five_minutes_hook&crontrol_sig=40cd750bba9870f18aada2478b24840a&crontrol_next_run_utc=1698757955) | [Draai nu](https://www.berkelland.net/wp-admin/tools.php?page=crontrol_admin_manage_page&crontrol_action=run-cron&crontrol_id=rsssl_every_five_minutes_hook&crontrol_sig=40cd750bba9870f18aada2478b24840a&crontrol_next_run_utc=1698757955&_wpnonce=c76f0ee898) | [Pauzeer deze hook](https://www.berkelland.net/wp-admin/tools.php?page=crontrol_admin_manage_page&crontrol_action=pause-hook&crontrol_id=rsssl_every_five_minutes_hook&_wpnonce=e0deb5d8bf) | [Verwijderen](https://www.berkelland.net/wp-admin/tools.php?page=crontrol_admin_manage_page&crontrol_action=delete-cron&crontrol_id=rsssl_every_five_minutes_hook&crontrol_sig=40cd750bba9870f18aada2478b24840a&crontrol_next_run_utc=1698757955&_wpnonce=8f540cb528)
	Geen	2023-10-31 13:12:35
3 minuten 19 seconden	rsssl_every_five_minutes_cron()	Once every 5 minutes

Publish on Atproto? is ON

**Comment by IDEA-ONLINE** [comment]
I installed to test a new clean wordpress, everything seems okay... but it doesn't work

**Comment by mbanusic** [comment]
I will update the project later tonight with some potential fixes. I will notify you so you can try it out.

**Comment by mbanusic** [comment]
Hi, please try the new [version](https://github.com/ne-znam/neznam-atproto-share/releases/download/1.1.1/neznam-atproto-share.zip) A fix with locale has been fixed.

**Comment by IDEA-ONLINE** [comment]
Thanks but is is not working
I removed the old, installed the new but I can't save the password after installation

This is what I see on screen:

string(12) "auth_request" array(6) { ["headers"]=> object(WpOrg\Requests\Utility\CaseInsensitiveDictionary)#1476 (1) { ["data":protected]=> array(11) { ["date"]=> string(29) "Thu, 02 Nov 2023 08:33:54 GMT" ["content-type"]=> string(31) "application/json; charset=utf-8" ["content-length"]=> string(3) "681" ["x-powered-by"]=> string(7) "Express" ["access-control-allow-origin"]=> string(1) "*" ["ratelimit-limit"]=> string(2) "30" ["ratelimit-remaining"]=> string(2) "27" ["ratelimit-reset"]=> string(10) "1698914224" ["ratelimit-policy"]=> string(8) "30;w=300" ["etag"]=> string(35) "W/"2a9-fuDkdvYnzEOJbWO5srpOSn4jz7Q"" ["vary"]=> string(15) "Accept-Encoding" } } ["body"]=> string(681) "{"did":"did:plc:jtnzf3t7mpr5ctkwmktuohqm","handle":"cryptonieuws.bsky.social","email":"eibergen@idea-online.nl","emailConfirmed":false,"accessJwt":"eyJhbGciOiJIU**

etcetc**

**Comment by ecaron** [comment]
@IDEA-ONLINE, with the release of 1.5.0, I believe the issue you're experiencing has been fixed. Can you try again?

**Comment by IDEA-ONLINE** [comment]
Hallo,

Wij zijn gesloten tot 7 januari 2025.
Alle mail naar dit adres wordt in deze periode niet gelezen. Wanneer u een spoedopdracht heeft neem dan contact met ons op via whatssapp.

Wij wensen u fijne kerstdagen en een voorspoedig 2025!

Met vriendelijke groet,

IDEA-ONLINE
