### ISSUE TITLE
Token refresh is not triggered

### ISSUE THREAD

**Issue by ecaron** [ne-znam/neznam-atproto-share#5]
I was running into a situation where the refresh token was expiring, and unless a blob was attached, there was no refresh attempted.

This can be resolved by a couple changes in `includes/class-neznam-atproto-share-logic.php`:
1. Add a `private bool $refresh_attempted = false;`
2. In `post_message` within the `if ( 200 !== $body['response']['code'] ) {`, add this:
```php
                        $response = isset( $body['body'] ) ? json_decode( $body['body'], true ) : [];
                        if ( ! $this->refresh_attempted && isset( $response['error'] ) && 'ExpiredToken' === $response['error'] ) {
                                $this->refresh_token();
                                $this->refresh_attempted = true;
                                $this->post_message ( $post );
                                return;
                        }
                        // TODO: Log error.
                        return;
```

With this change, it hopes the current token is valid. In the event it fails for expiration, it makes sure we only attempt a refresh once.

@mbanusic - would you accept a PR for this logic?

**Comment by mbanusic** [comment]
I would, send over and I'll check it out and merge

**Comment by mbanusic** [comment]
Also send other issue fixes

**Comment by ecaron** [comment]
@mbanusic PRs have been submitted. Please let me know if I should do anything different to better accommodate your workflows.

If you're good with these, I'd like to take a swing at getting the debug and error logging included, which you mentioned in a couple TODO notes.
